package com.graduation.pro.study_system.pojo;

public class Users {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.Id
	 * @mbggenerated  Thu Mar 19 14:41:31 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.username
	 * @mbggenerated  Thu Mar 19 14:41:31 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.age
	 * @mbggenerated  Thu Mar 19 14:41:31 CST 2015
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.email
	 * @mbggenerated  Thu Mar 19 14:41:31 CST 2015
	 */
	private String email;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.Id
	 * @return  the value of users.Id
	 * @mbggenerated  Thu Mar 19 14:41:31 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.Id
	 * @param id  the value for users.Id
	 * @mbggenerated  Thu Mar 19 14:41:31 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.username
	 * @return  the value of users.username
	 * @mbggenerated  Thu Mar 19 14:41:31 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.username
	 * @param username  the value for users.username
	 * @mbggenerated  Thu Mar 19 14:41:31 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.age
	 * @return  the value of users.age
	 * @mbggenerated  Thu Mar 19 14:41:31 CST 2015
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.age
	 * @param age  the value for users.age
	 * @mbggenerated  Thu Mar 19 14:41:31 CST 2015
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.email
	 * @return  the value of users.email
	 * @mbggenerated  Thu Mar 19 14:41:31 CST 2015
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.email
	 * @param email  the value for users.email
	 * @mbggenerated  Thu Mar 19 14:41:31 CST 2015
	 */
	public void setEmail(String email) {
		this.email = email;
	}
}